# Site settings
title: Suvarna Kadam
twitter_username: suvarna
name: Suvarna Kadam

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://deep-experiments.blogspot.com/
 - title: GitHub
   url: https://github.com/suvarnak
 - title: StackOverflow
   url: https://stackoverflow.com/users/2769865/suvarna-kadam
 - title: Youtube
   url: 
 - title: LinkedIn
   url:https://www.linkedin.com/in/suvarna-kadam-a3191613/

#Any buzzword skills you want to include
skills:
 - Deep Neural Networks
 - Machine Learning
 - Deep Learning Frameworks (TensorFlow, Keras, PyTorch)
 - Python
 - JavaScript
 - Java
 - Goole Colab
 - AWS
 - Google App.js
 
#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Machine Learning Engineer
   start: 2020
   end: Ongoing
   employer: 
   description: 
 - title: PhD Student
   start: 2016
   end: 2017
   employer: Emerald Street Ventures
   description: Emerald Street Ventures was established as an incubator vehicle for the development of a number of software and legal-tech projects, and a rapidly growing, London-based start-up using innovative technologies to revolutionise and change the software and legal-tech landscape. Working with a range of cutting edge technologies and techniques including Scala, Cassandra, CoreOS, a variety of Machine Learning techniques.
 - title: Senior Engineer
   start: 2012
   end: 2016
   employer: Covestor
   description: Covestor is an investment marketplace startup that was successfully acquired by Interactive Brokers in 2015. <br/> Working as a senior engineer, I worked closely with the CTO and across the full-stack, I was involved in all aspects of the technology including the website and back-end services.
 - title: Associate Manager
   start: 2005
   end: 2012
   employer: Accenture
   description: Working on a range of functional and technical roles, primarily working on client sites in Financial Services in London and Europe.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2003
   subject: Artificial Intelligence and Computer Science
   school: University of Birmingham

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: Algorithms Design and Analysis, Part 1
      link: https://www.coursera.org/specializations/algorithms
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014


#List of interesting Github repo/projects to include - optional
github:
 - suvarnak/trashdump_detection
 - suvarnak/PythonSkillDevelopmentLab
 - suvarnak/TL_demo

#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/258813/rhinds
   flairimageurl: http://stackoverflow.com/users/flair/258813.png

intro: |
I am a Machine Learning Engineer, currently pursuing PhD in few shot learning from university of Pune. I have done few PoC in computer vision and deep learning(object detection) as contracting work. You may find few demo videos at https://drive.google.com/open?id=1IP6VqfMrGEzwmhPgca0WNvCV2LkTmrQI. I am good at reading research papers and replicating and customizing the SOTA research work. I have some experience of running ML experiments on AWS, Google Colab and MS Azure.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Tensorflow</strong>: My current role uses Tensorflow as the primary ML framework and have been building applications in ML and Computer Vision for the last three years. I am familiar with a range of OpenCV Functionalities.
   
